Closes OFE-100: Fixed bonding responsive
onomyprotocol/otrust pull request #186
Opened 2021-09-02 13:08 UTC by bbshark99

2021-09-02 13:22 UTC, AndriiBlagodyr commented on src/theme/constants.js
> +  laptopSmall: '1300px',
This change requires retesting of the whole application for tablet/laptopSmall/laptop sizes. @bbshark99  Does all tabs and modals now have a correct view for the mentioned width? I'm asking just to be sure that we didn't break anything with this change. Thanks.

2021-09-02 13:53 UTC, bbshark99 commented on src/theme/constants.js
> +  laptopSmall: '1300px',
@AndriiBlagodyr I think adding new variable might be better. like below:
```
{
  laptopMedium: '1300px',
  laptopSmall: '1180px',
}
```

2021-09-02 14:25 UTC, bbshark99 commented
@AndriiBlagodyr added `laptop-medium: 1300`

2021-09-02 20:04 UTC, flppv requested changes
These tasks can be completed without adding an extra breakpoint. 
As for the footer overlap, need to move it to the bottom;
As for the buy/sell forms need to adjust grid, so items will take 50% of the width.

2021-09-02 23:46 UTC, bbshark99 commented
@flppv Fixed

2021-09-05 10:01 UTC, flppv approved these changes

2021-09-05 10:01 UTC, merged